version: 2
builds:
  - id: xct
    main: cmd/xct/main.go
    binary: xct
    ldflags:
      - -s -w -X main.BuildVersion={{.Version}}
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
changelog:
  disable: false
  use: github
  sort: asc
  groups:
    - title: Features
      regexp: '^feat(\([\w-]+\))?!?:.*'
      order: 0
    - title: "Bug Fixes"
      regexp: '^fix(\([\w-]+\))?!?:.*'
      order: 1
    - title: "Refactor"
      regexp: '^refactor(\([\w-]+\))?!?:.*'
      order: 2
    - title: "Build Process Updates"
      regexp: '^(build|ci)(\([\w-]+\))?!?:.*'
      order: 3
    - title: "Documentation Updates"
      regexp: '^docs(\([\w-]+\))?!?:.*'
      order: 4
    - title: "Maintenance"
      regexp: '^chore(\([\w-]+\))?!?:.*'
      order: 5
    - title: Others
      order: 999
